### ISSUE TITLE
Add mayLaunchUrl and warmup methods in Android

### ISSUE THREAD

**Issue by LuckyLuke19** [matei-radu/react-native-in-app-browser#69]

**Comment by matei-radu** [comment]
Thanks for bringing these up.

At first glance, they seem easy to implement, so they will most likely make it into the next update for both v2 and v3.

**Resources for later**
- [CustomTabsSession - mayLaunchUrl](https://developer.android.com/reference/android/support/customtabs/CustomTabsSession.html#maylaunchurl)
- [CustomTabsClient - warmup](https://developer.android.com/reference/android/support/customtabs/CustomTabsClient.html#warmup)

**Comment by matei-radu** [comment]
@LuckyLuke19 could try out the latest release candidate with the two new methods?

```sh
@matt-block/react-native-in-app-browser@next
```

**Comment by LuckyLuke19** [comment]
@matei-radu It works, thanks!
