### ISSUE TITLE
Provide option to control modal transition style

### ISSUE THREAD

**Issue by achou11** [matei-radu/react-native-in-app-browser#73]
It would be great to be able to have a setting that customizes the transition style of the modal when it opens/closes. I noticed that the way I currently have it set up, it comes in from the bottom on Android, whereas it comes in from the side on iOS. Would love to make it consistent for my use case.

Just from a quick search, seems like this is the relevant property for iOS:

- https://developer.apple.com/documentation/uikit/uiviewcontroller/1621388-modaltransitionstyle
- https://developer.apple.com/documentation/uikit/uimodaltransitionstyle

Not sure what the equivalent is on Android but I would imagine that they have something similar.

**Comment by matei-radu** [comment]
I'll have to check over the weekend if the [`SFSafariViewController`](https://developer.apple.com/documentation/safariservices/sfsafariviewcontroller) allows to change the transitions. It does inherit from `UIViewController` but it also seems to behave a bit differently.

For Android, the Chrome Custom Tabs Build allows to easily set start and exit animations:

- [`CustonTabsIntent.Builder setStartAnimations`](https://developer.android.com/reference/android/support/customtabs/CustomTabsIntent.Builder#setstartanimations)
- [`CustonTabsIntent.Builder setExitAnimations`](https://developer.android.com/reference/android/support/customtabs/CustomTabsIntent.Builder#setexitanimations)

**Comment by achou11** [comment]
Ah got it 👍 It would be great to have this implemented, as it's the one main thing that's missing imo :)

**Comment by matei-radu** [comment]
@achou11 I had a look and it's definitely doable.

However, this month I'm quite busy at work and I'm not sure when I would find some time to work on this.

If you're in a rush, you could have a look at [react-native-inappbrowser-reborn](https://github.com/proyecto26/react-native-inappbrowser) which is another great library and might already support these presentational aspects. Maybe @jdnichollsc can give us an insight 👋 😄

**Comment by jdnichollsc** [comment]
haha hi friends! yeah, let me know any issue from that repo 👍 
I'm using Objective C instead, but is very similar, check the code to support that: https://github.com/proyecto26/react-native-inappbrowser/blob/master/ios/RNInAppBrowser.m#L142

**Comment by matei-radu** [comment]
Closing as this project has reached EOL.
