### ISSUE TITLE
How to change Bottom navigation bar color ?

### ISSUE THREAD

**Issue by nakinthorn** [matei-radu/react-native-in-app-browser#99]
How to change Bottom navigation bar color ?

Android:
it can change toorbarColor (top bar)
but.. 
Why it cannot change Bottom navigation ?
Or maybe me stupid..

pls help

**Comment by matei-radu** [comment]
Hi!

Unfortunately, the Android API (Chrome Custom Tabs) does not allow to change the navigation bar colors.
